name: Build Apk

on: 
  push:
    tags: [release]
  workflow_dispatch:

jobs:
  Gradle:
    runs-on: windows-2022
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup jdk
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 17
    - name: Make Gradle executable
      run: chmod +x ./LinspirerDemo-master/gradlew
    - name: Copy important files
      run: |
        mkdir ./LinspirerDemo-master/app/src/main/java/com/ljlVink/core/core
        cp .github/IPostcallback.java ./LinspirerDemo-master/app/src/main/java/com/ljlVink/core/core
        cp .github/Postutil.java ./LinspirerDemo-master/app/src/main/java/com/ljlVink/core/core
        rm LinspirerDemo-master/app/src/main/java/com/ljlVink/lsphunter/BaseActivity.java
        cp .github/BaseActivity.java ./LinspirerDemo-master/app/src/main/java/com/ljlVink/lsphunter
    - name: Clone base app and Build Release APK
      run: |
        cd ./LinspirerDemo-master
        git clone https://github.com/ljlVink/HackMdm-core hackmdm
        ./gradlew aR
    - name: Upload apk
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: LinspirerDemo-master/app/build/outputs/apk